#!/bin/sh

git clean -fdx && \
npm cache clear && \
npm i --no-optional && \
npm link --no-optional && \
npm pack && \
npm uninstall -g mandarinajs && \
npm i -g ./mandarinajs-*.tgz && \
du -sh ./mandarinajs-*.tgz
